version: "3"

services:
#     nginx-proxy:
#      image: jwilder/nginx-proxy
#      container_name: nginx-proxy
#      ports:
#        - "80:80"
#      volumes:
#        - /var/run/docker.sock:/tmp/docker.sock:ro

     php:
      image: dmiseev/php-fpm7.2
      working_dir: /app
      volumes:
        - .:/app
      expose:
        - 9000
#      depends_on:
#        - mysql
#      links:
#        - mysql

     nginx:
      image: nginx:1.15
      volumes:
       - ./default.conf:/etc/nginx/conf.d/default.conf
       - .:/app
#      expose:
#        - 80
      ports:
        - "8011:80"
      environment:
        VIRTUAL_HOST: mvc.loc
      depends_on:
        - php
      links:
        - php
      restart: always

#     mysql:
#      image: mysql:5.7
#      volumes:
#        - ./docker/db_data:/var/lib/mysql
#        - ./docker/db_dump:/docker-entrypoint-initdb.d
#      restart: always
#      environment:
#        MYSQL_ROOT_PASSWORD: root
#        MYSQL_DATABASE: wp_db
#        MYSQL_USER: wp_u
#        MYSQL_PASSWORD: wp_pas
#
#     phpmyadmin:
#      image: phpmyadmin/phpmyadmin
#      depends_on:
#        - mysql
#      links:
#        - mysql:db
#      environment:
#        VIRTUAL_HOST: pma.wp.loc
#        MYSQL_ROOT_PASSWORD: root
#      restart: always
#
#     composer:
#      restart: 'no'
#      image: composer
#      command: install
#      volumes:
#        - ./src:/app

networks:
  default:
    external:
      name: nginx-proxy