<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container56mv46Y\publicKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container56mv46Y/publicKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container56mv46Y.legacy');

    return;
}

if (!\class_exists(publicKernelDevDebugContainer::class, false)) {
    \class_alias(\Container56mv46Y\publicKernelDevDebugContainer::class, publicKernelDevDebugContainer::class, false);
}

return new \Container56mv46Y\publicKernelDevDebugContainer(array(
    'container.build_hash' => '56mv46Y',
    'container.build_id' => '0c4cd455',
    'container.build_time' => 1546393383,
), __DIR__.\DIRECTORY_SEPARATOR.'Container56mv46Y');
