<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEdgjXQg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEdgjXQg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEdgjXQg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEdgjXQg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEdgjXQg\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'EdgjXQg',
    'container.build_id' => 'eb21e2f0',
    'container.build_time' => 1546394597,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEdgjXQg');
